
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.homee.mapboxnavigation;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import android.graphics.Rect;
import com.facebook.react.bridge.ReactModuleWithSpec;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public abstract class NativeMapboxNavigationViewModuleSpec extends ReactContextBaseJavaModule implements ReactModuleWithSpec, TurboModule {
  public static final String NAME = "MapboxNavigationViewModule";

  public NativeMapboxNavigationViewModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void startFreeDrive(@Nullable Double viewRef, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void stopFreeDrive(@Nullable Double viewRef, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void startNavigation(@Nullable Double viewRef, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void stopNavigation(@Nullable Double viewRef, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void showRoutePreview(@Nullable Double viewRef, ReadableArray coordinates, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void hideRoutePreview(@Nullable Double viewRef, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setCameraZoom(@Nullable Double viewRef, Double zoomLevel, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getCameraZoom(@Nullable Double viewRef, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setVisibleArea(@Nullable Double viewRef, ReadableMap visibleArea, Promise promise);
}
