/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import com.facebook.react.bridge.Dynamic;

public interface MapboxNavigationViewManagerInterface<T extends View> {
  void setDefaultCameraOptions(T view, Dynamic value);
  void setOrigin(T view, Dynamic value);
  void setDestination(T view, Dynamic value);
  void setShouldSimulateRoute(T view, Dynamic value);
  void setShowsEndOfRouteFeedback(T view, Dynamic value);
  void setMute(T view, Dynamic value);
  void setViewStyles(T view, Dynamic value);
  void setIsCarplayView(T view, Dynamic value);
  void setFreeDriveEnabled(T view, Dynamic value);
  void setMapStyleURL(T view, Dynamic value);
  void setIsDarkMode(T view, Dynamic value);
}