/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.DynamicFromObject;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.BaseViewManagerInterface;

public class MapboxNavigationViewManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & MapboxNavigationViewManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public MapboxNavigationViewManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "origin":
        mViewManager.setOrigin(view, new DynamicFromObject(value));
        break;
      case "destination":
        mViewManager.setDestination(view, new DynamicFromObject(value));
        break;
      case "shouldSimulateRoute":
        mViewManager.setShouldSimulateRoute(view, new DynamicFromObject(value));
        break;
      case "showsEndOfRouteFeedback":
        mViewManager.setShowsEndOfRouteFeedback(view, new DynamicFromObject(value));
        break;
      case "mute":
        mViewManager.setMute(view, new DynamicFromObject(value));
        break;
      case "viewStyles":
        mViewManager.setViewStyles(view, new DynamicFromObject(value));
        break;
      case "isCarplayView":
        mViewManager.setIsCarplayView(view, new DynamicFromObject(value));
        break;
      case "freeDrive":
        mViewManager.setFreeDriveEnabled(view, new DynamicFromObject(value));
        break;
      case "mapStyleURL":
        mViewManager.setMapStyleURL(view, new DynamicFromObject(value));
        break;
      case "isDarkMode":
        mViewManager.setIsDarkMode(view, new DynamicFromObject(value));
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }
}
